### ISSUE TITLE
goose installed with pipx fails due to TypeError

### ISSUE THREAD

**Issue by jtorreggiani** [block-open-source/goose#171]
I installed goose via `pipx install goose-ai`. Any goose command I try I get the following stack trace. goose fails regardless of the folder I am in.

```
Traceback (most recent call last):
  File "/Users/jtorreggiani/.local/bin/goose", line 5, in <module>
    from goose.cli.main import cli
  File "/Users/jtorreggiani/.local/pipx/venvs/goose-ai/lib/python3.13/site-packages/goose/cli/main.py", line 10, in <module>
    from goose.cli.config import SESSIONS_PATH
  File "/Users/jtorreggiani/.local/pipx/venvs/goose-ai/lib/python3.13/site-packages/goose/cli/config.py", line 9, in <module>
    from exchange.providers.ollama import OLLAMA_MODEL
  File "/Users/jtorreggiani/.local/pipx/venvs/goose-ai/lib/python3.13/site-packages/exchange/__init__.py", line 6, in <module>
    from exchange.exchange import Exchange  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jtorreggiani/.local/pipx/venvs/goose-ai/lib/python3.13/site-packages/exchange/exchange.py", line 6, in <module>
    from exchange.langfuse_wrapper import observe_wrapper
  File "/Users/jtorreggiani/.local/pipx/venvs/goose-ai/lib/python3.13/site-packages/exchange/langfuse_wrapper.py", line 51, in <module>
    LANGFUSE_ENV_FILE = os.path.join(PACKAGE_ROOT, ".env.langfuse.local")
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I am able to get goose running using the contributing documentation https://block-open-source.github.io/goose/contributing.html#run-tests. 

Wondering if there are their conflicts with running the development version and version install with pipx.

**Comment by lamchau** [comment]
so we just cut a release, right now the most stable release is 0.9.5 as long as you're running python<3.13 - so try `pipx install goose-ai==0.9.5` for now. otherwise `uv run goose` is how to run it
